//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCheckInCheckOut.Web.Controls {
    
    
    public partial class _SideBar {
        
        /// <summary>
        /// _SideBarFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookCheckInCheckOut.Web.Controls._SideBarFooter _SideBarFooter;
    }
}
